// 点検用：一時停止のボタンで時計が止まり、続けるで動くか・昼の番犬は1回目のタップで選ばれ、2回目で外れるか
import { chromium } from 'playwright';
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { extname, join } from 'node:path';
const T = { '.js': 'text/javascript', '.css': 'text/css', '.webp': 'image/webp', '.json': 'application/json', '.svg': 'image/svg+xml' };
const root = new URL('../app/dist', import.meta.url).pathname;
const srv = createServer(async (q, s) => { let p = new URL(q.url, 'http://x').pathname.replace(/^\/akazukin/, ''); if (p === '/') p = '/index.html'; try { const b = await readFile(join(root, p)); s.writeHead(200, { 'content-type': T[extname(p)] || 'text/html' }); s.end(b); } catch { s.writeHead(404).end(); } });
await new Promise((r) => srv.listen(0, r));
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const p = await b.newPage({ viewport: { width: 390, height: 844 } });
const errors = []; p.on('pageerror', (e) => errors.push(e.message));
await p.goto(`http://127.0.0.1:${srv.address().port}/akazukin/?auto=1`);
await p.waitForFunction(() => document.body.classList.contains('ready'));
await p.waitForTimeout(1500);
const out = {};
await p.click('#pause');
const c0 = await p.evaluate(() => window.akazukin.sim.clock);
await p.waitForTimeout(800);
out.pausedClockDelta = await p.evaluate((c) => window.akazukin.sim.clock - c, c0);
out.overlay = await p.evaluate(() => document.getElementById('overlay').innerText.slice(0, 20));
await p.click('#overlay button');
await p.waitForTimeout(800);
out.resumedClockDelta = await p.evaluate((c) => window.akazukin.sim.clock - c, c0);
// 昼：番犬の札をタップすると役目が 守り → 攻撃 → 支援 と変わる
await p.evaluate(() => { const s = window.akazukin.sim; s.wolves = []; s.spawners = []; s.phase = 'shop'; });
await p.waitForTimeout(600);
out.roleBefore = await p.evaluate(() => window.akazukin.sim.roles.shiba);
await p.click('.dog');
await p.waitForTimeout(100);
out.roleAfter = await p.evaluate(() => window.akazukin.sim.roles.shiba);
out.errors = errors;
console.log(JSON.stringify(out));
await b.close(); srv.close();
